#!/usr/bin/env bash
set -euo pipefail

REGION="us-east-1"
PROFILE=""
COUNT=""
PLAN_FILE=""
DRY_RUN=false
INCLUDE_CLIENT=true

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REGIONS_FILE_PATH="$SCRIPT_DIR/regions.txt"

TOTAL_CLIENTS=0
TOTAL_NON_CLIENTS=0
TOTAL_REGION_ACTIONS=0

export AWS_PAGER=""

usage() {
  cat <<'USAGE'
Usage: ./start_instances.sh [--region REGION] [--profile PROFILE] [--count N] [--dry-run]
                            [--no-client] [--plan plan.json]

Starts stopped EC2 instances:
  - Always starts 'client' if it's stopped
  - Starts N other stopped instances (excluding 'client')
  - If --count is omitted, starts all stopped (client + others)
  - --plan lets you describe multiple regions/counts in JSON (see start-plan.example.json)
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --region) REGION="$2"; shift 2;;
    --profile) PROFILE="$2"; shift 2;;
    --count) COUNT="$2"; shift 2;;
    --plan) PLAN_FILE="$2"; shift 2;;
    --no-client) INCLUDE_CLIENT=false; shift;;
    --dry-run) DRY_RUN=true; shift;;
    -h|--help) usage; exit 0;;
    *) echo "Unknown arg $1"; usage; exit 1;;
  esac
done

normalize_bool() {
  local value="${1:-true}"
  value=$(tr '[:upper:]' '[:lower:]' <<<"$value")
  case "$value" in
    false|0|no|disabled) echo "false" ;;
    *) echo "true" ;;
  esac
}

write_regions_file() {
  local -a regions=("$@")
  if (( ${#regions[@]} == 0 )); then
    echo "No regions provided to write_regions_file" >&2
    return 1
  fi

  {
    echo "# Auto-generated by start_instances.sh on $(date '+%Y-%m-%d %H:%M:%S')"
    for region in "${regions[@]}"; do
      echo "$region"
    done
  } > "$REGIONS_FILE_PATH"

  echo "✓ Updated regions file: $REGIONS_FILE_PATH (${regions[*]})"
}

record_region_totals() {
  local clients="$1"
  local non_clients="$2"
  TOTAL_CLIENTS=$((TOTAL_CLIENTS + clients))
  TOTAL_NON_CLIENTS=$((TOTAL_NON_CLIENTS + non_clients))
  TOTAL_REGION_ACTIONS=$((TOTAL_REGION_ACTIONS + 1))
}

print_summary() {
  local total_instances=$((TOTAL_CLIENTS + TOTAL_NON_CLIENTS))
  if (( TOTAL_REGION_ACTIONS == 0 )); then
    if $DRY_RUN; then
      echo "Dry run summary: nothing to start"
    else
      echo "Summary: nothing started"
    fi
    return
  fi

  if $DRY_RUN; then
    echo "Dry run summary: would start ${total_instances} instance(s) across ${TOTAL_REGION_ACTIONS} region(s) (clients: ${TOTAL_CLIENTS}, non-clients: ${TOTAL_NON_CLIENTS})."
  else
    echo "Summary: started ${total_instances} instance(s) across ${TOTAL_REGION_ACTIONS} region(s) (clients: ${TOTAL_CLIENTS}, non-clients: ${TOTAL_NON_CLIENTS})."
  fi
}

start_region_instances() {
  local region="$1"
  local profile="$2"
  local count_input="$3"
  local include_client="$(normalize_bool "${4:-true}")"

  local aws_cmd=(aws)
  [[ -n "$region" ]] && aws_cmd+=(--region "$region")
  [[ -n "$profile" ]] && aws_cmd+=(--profile "$profile")

  mapfile -t lines < <("${aws_cmd[@]}" ec2 describe-instances \
    --filters "Name=instance-state-name,Values=stopped" \
    --query "Reservations[].Instances[].{Id:InstanceId,Name:Tags[?Key=='Name']|[0].Value}" \
    --output text)

  declare -a pool_ids=()
  local client_id=""

  for line in "${lines[@]}"; do
    [[ -z "$line" || "$line" == "None" ]] && continue
    local id name
    read -r id name _ <<<"$line"
    if [[ "$name" == "client" ]]; then
      client_id="$id"
    else
      pool_ids+=("$id")
    fi
  done

  if [[ "$include_client" == "true" && -z "$client_id" ]]; then
    echo "⚠️  [${region:-default}] No stopped 'client' instance found (skipping client)."
  fi

  local requested_count="$count_input"
  if [[ -n "$requested_count" && ! "$requested_count" =~ ^[0-9]+$ ]]; then
    echo "❌ Invalid --count value '$requested_count' for region ${region}" >&2
    exit 1
  fi

  local available=${#pool_ids[@]}
  local count
  if [[ -z "$requested_count" ]]; then
    count=$available
  else
    count=$requested_count
  fi

  if (( count > available )); then
    echo "⚠️  [${region:-default}] Requested $count non-client nodes but only $available available; using $available."
    count=$available
  fi

  local selected_ids=("${pool_ids[@]:0:$count}")
  local final_ids=()
  local client_count=0

  if [[ "$include_client" == "true" && -n "$client_id" ]]; then
    final_ids+=("$client_id")
    client_count=1
  fi
  final_ids+=("${selected_ids[@]}")

  local non_client_count=${#selected_ids[@]}
  local total_count=${#final_ids[@]}

  if (( total_count == 0 )); then
    echo "Nothing to start in region ${region:-default}."
    return
  fi

  if $DRY_RUN; then
    echo "✨ Dry run [${region:-default}]: would start ${total_count} instance(s) (clients: ${client_count}, non-clients: ${non_client_count}):"
    printf '  %s\n' "${final_ids[@]}"
    record_region_totals "$client_count" "$non_client_count"
    return
  fi

  "${aws_cmd[@]}" ec2 start-instances --instance-ids "${final_ids[@]}"
  echo "Started instances in ${region:-default} (${total_count} total, clients: ${client_count}, non-clients: ${non_client_count}):"
  printf '  %s\n' "${final_ids[@]}"
  record_region_totals "$client_count" "$non_client_count"
}

run_plan() {
  if [[ -z "$PLAN_FILE" ]]; then
    return 1
  fi

  if ! command -v jq >/dev/null 2>&1; then
    echo "jq is required to use --plan" >&2
    exit 1
  fi

  if [[ ! -f "$PLAN_FILE" ]]; then
    echo "Plan file '$PLAN_FILE' does not exist" >&2
    exit 1
  fi

  mapfile -t PLAN_REGIONS_RAW < <(jq -r '.regions[]?.region // empty' "$PLAN_FILE" | awk 'NF > 0')
  if (( ${#PLAN_REGIONS_RAW[@]} == 0 )); then
    echo "Plan file '$PLAN_FILE' does not contain any regions" >&2
    exit 1
  fi
  mapfile -t PLAN_REGIONS < <(printf '%s\n' "${PLAN_REGIONS_RAW[@]}" | awk '!seen[$0]++')

  local entries
  entries=$(jq -c '.regions // [] | .[]' "$PLAN_FILE")
  if [[ -z "$entries" ]]; then
    echo "Plan file '$PLAN_FILE' has no regions[] entries" >&2
    exit 1
  fi

  if $DRY_RUN; then
    echo "ℹ️ Dry run: would update regions file ($REGIONS_FILE_PATH) with: ${PLAN_REGIONS[*]}"
  else
    write_regions_file "${PLAN_REGIONS[@]}"
  fi

  while IFS= read -r entry; do
    local region profile count include_client
    region=$(jq -r '.region // empty' <<<"$entry")
    if [[ -z "$region" ]]; then
      echo "Plan entry missing 'region'" >&2
      exit 1
    fi
    profile=$(jq -r '.profile // ""' <<<"$entry")
    count=$(jq -r '.count // ""' <<<"$entry")
    if jq -e 'has("include_client")' >/dev/null <<<"$entry"; then
      include_client=$(jq -r '.include_client' <<<"$entry")
    else
      include_client="$INCLUDE_CLIENT"
    fi

    start_region_instances "$region" "$profile" "$count" "$include_client"
  done <<<"$entries"

  return 0
}

if run_plan; then
  print_summary
  exit 0
fi

start_region_instances "$REGION" "$PROFILE" "$COUNT" "$INCLUDE_CLIENT"
print_summary
